version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      -"5432:5432"

  pipeline:
    build: ./pipeline
    container_name: pipeline
    environment:
      DB_HOST: "postgres"
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      OPEN_ROUTE_KEY: ${OPEN_ROUTE_KEY}
    depends_on:
      - postgres

  telegram_bot:
    build: ./tel_bot
    container_name: bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - pipeline

